// Code generated by protoc-gen-go.
// source: protos/broker.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	protos/broker.proto

It has these top-level messages:
	InstrumentListReq
	InstrumentListResp
	PriceListReq
	PriceListResp
	LastCandleReq
	LastCandleResp
	StreamPricesReq
	StreamCandleReq
	AccountListReq
	AccountListResp
	AccountInfoReq
	AccountInfoResp
	OrderListReq
	OrderListResp
	CloseTradeReq
	CloseTradeResp
	OrderCreationReq
	OrderCreationResp
	Quote
	Candle
	Empty
	Instrument
	Account
	AccountInfo
	Order
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InstrumentListReq struct {
	AccountId string `protobuf:"bytes,2,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *InstrumentListReq) Reset()                    { *m = InstrumentListReq{} }
func (m *InstrumentListReq) String() string            { return proto.CompactTextString(m) }
func (*InstrumentListReq) ProtoMessage()               {}
func (*InstrumentListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InstrumentListResp struct {
	Instruments []*Instrument `protobuf:"bytes,1,rep,name=instruments" json:"instruments,omitempty"`
}

func (m *InstrumentListResp) Reset()                    { *m = InstrumentListResp{} }
func (m *InstrumentListResp) String() string            { return proto.CompactTextString(m) }
func (*InstrumentListResp) ProtoMessage()               {}
func (*InstrumentListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InstrumentListResp) GetInstruments() []*Instrument {
	if m != nil {
		return m.Instruments
	}
	return nil
}

type PriceListReq struct {
	InstrumentId []string `protobuf:"bytes,2,rep,name=instrumentId" json:"instrumentId,omitempty"`
}

func (m *PriceListReq) Reset()                    { *m = PriceListReq{} }
func (m *PriceListReq) String() string            { return proto.CompactTextString(m) }
func (*PriceListReq) ProtoMessage()               {}
func (*PriceListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PriceListResp struct {
	Quotes []*Quote `protobuf:"bytes,1,rep,name=quotes" json:"quotes,omitempty"`
}

func (m *PriceListResp) Reset()                    { *m = PriceListResp{} }
func (m *PriceListResp) String() string            { return proto.CompactTextString(m) }
func (*PriceListResp) ProtoMessage()               {}
func (*PriceListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PriceListResp) GetQuotes() []*Quote {
	if m != nil {
		return m.Quotes
	}
	return nil
}

type LastCandleReq struct {
	InstrumentId string `protobuf:"bytes,2,opt,name=instrumentId" json:"instrumentId,omitempty"`
}

func (m *LastCandleReq) Reset()                    { *m = LastCandleReq{} }
func (m *LastCandleReq) String() string            { return proto.CompactTextString(m) }
func (*LastCandleReq) ProtoMessage()               {}
func (*LastCandleReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type LastCandleResp struct {
	Candle *Candle `protobuf:"bytes,1,opt,name=candle" json:"candle,omitempty"`
}

func (m *LastCandleResp) Reset()                    { *m = LastCandleResp{} }
func (m *LastCandleResp) String() string            { return proto.CompactTextString(m) }
func (*LastCandleResp) ProtoMessage()               {}
func (*LastCandleResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LastCandleResp) GetCandle() *Candle {
	if m != nil {
		return m.Candle
	}
	return nil
}

type StreamPricesReq struct {
	InstrumentId string `protobuf:"bytes,2,opt,name=instrumentId" json:"instrumentId,omitempty"`
}

func (m *StreamPricesReq) Reset()                    { *m = StreamPricesReq{} }
func (m *StreamPricesReq) String() string            { return proto.CompactTextString(m) }
func (*StreamPricesReq) ProtoMessage()               {}
func (*StreamPricesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type StreamCandleReq struct {
	InstrumentId string `protobuf:"bytes,2,opt,name=instrumentId" json:"instrumentId,omitempty"`
}

func (m *StreamCandleReq) Reset()                    { *m = StreamCandleReq{} }
func (m *StreamCandleReq) String() string            { return proto.CompactTextString(m) }
func (*StreamCandleReq) ProtoMessage()               {}
func (*StreamCandleReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AccountListReq struct {
}

func (m *AccountListReq) Reset()                    { *m = AccountListReq{} }
func (m *AccountListReq) String() string            { return proto.CompactTextString(m) }
func (*AccountListReq) ProtoMessage()               {}
func (*AccountListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type AccountListResp struct {
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
}

func (m *AccountListResp) Reset()                    { *m = AccountListResp{} }
func (m *AccountListResp) String() string            { return proto.CompactTextString(m) }
func (*AccountListResp) ProtoMessage()               {}
func (*AccountListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AccountListResp) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type AccountInfoReq struct {
	AccountId string `protobuf:"bytes,2,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *AccountInfoReq) Reset()                    { *m = AccountInfoReq{} }
func (m *AccountInfoReq) String() string            { return proto.CompactTextString(m) }
func (*AccountInfoReq) ProtoMessage()               {}
func (*AccountInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type AccountInfoResp struct {
	Info *AccountInfo `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *AccountInfoResp) Reset()                    { *m = AccountInfoResp{} }
func (m *AccountInfoResp) String() string            { return proto.CompactTextString(m) }
func (*AccountInfoResp) ProtoMessage()               {}
func (*AccountInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AccountInfoResp) GetInfo() *AccountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type OrderListReq struct {
	AccountId string `protobuf:"bytes,2,opt,name=accountId" json:"accountId,omitempty"`
}

func (m *OrderListReq) Reset()                    { *m = OrderListReq{} }
func (m *OrderListReq) String() string            { return proto.CompactTextString(m) }
func (*OrderListReq) ProtoMessage()               {}
func (*OrderListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type OrderListResp struct {
	Orders []*Order `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty"`
}

func (m *OrderListResp) Reset()                    { *m = OrderListResp{} }
func (m *OrderListResp) String() string            { return proto.CompactTextString(m) }
func (*OrderListResp) ProtoMessage()               {}
func (*OrderListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *OrderListResp) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type CloseTradeReq struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CloseTradeReq) Reset()                    { *m = CloseTradeReq{} }
func (m *CloseTradeReq) String() string            { return proto.CompactTextString(m) }
func (*CloseTradeReq) ProtoMessage()               {}
func (*CloseTradeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type CloseTradeResp struct {
	Id           string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Price        float64 `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	InstrumentId string  `protobuf:"bytes,3,opt,name=instrumentId" json:"instrumentId,omitempty"`
	Time         string  `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	Profit       float64 `protobuf:"fixed64,5,opt,name=profit" json:"profit,omitempty"`
	Side         string  `protobuf:"bytes,6,opt,name=side" json:"side,omitempty"`
}

func (m *CloseTradeResp) Reset()                    { *m = CloseTradeResp{} }
func (m *CloseTradeResp) String() string            { return proto.CompactTextString(m) }
func (*CloseTradeResp) ProtoMessage()               {}
func (*CloseTradeResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type OrderCreationReq struct {
	InstrumentId string `protobuf:"bytes,2,opt,name=instrumentId" json:"instrumentId,omitempty"`
	Units        int32  `protobuf:"varint,3,opt,name=units" json:"units,omitempty"`
	Side         string `protobuf:"bytes,4,opt,name=side" json:"side,omitempty"`
	Type         string `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
}

func (m *OrderCreationReq) Reset()                    { *m = OrderCreationReq{} }
func (m *OrderCreationReq) String() string            { return proto.CompactTextString(m) }
func (*OrderCreationReq) ProtoMessage()               {}
func (*OrderCreationReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type OrderCreationResp struct {
	InstrumentId string  `protobuf:"bytes,1,opt,name=instrumentId" json:"instrumentId,omitempty"`
	Price        float64 `protobuf:"fixed64,2,opt,name=price" json:"price,omitempty"`
	Time         string  `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
	Id           string  `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
}

func (m *OrderCreationResp) Reset()                    { *m = OrderCreationResp{} }
func (m *OrderCreationResp) String() string            { return proto.CompactTextString(m) }
func (*OrderCreationResp) ProtoMessage()               {}
func (*OrderCreationResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type Quote struct {
	InstrumentId string  `protobuf:"bytes,1,opt,name=instrumentId" json:"instrumentId,omitempty"`
	Bid          float64 `protobuf:"fixed64,2,opt,name=bid" json:"bid,omitempty"`
	Ask          float64 `protobuf:"fixed64,3,opt,name=ask" json:"ask,omitempty"`
	Time         string  `protobuf:"bytes,4,opt,name=time" json:"time,omitempty"`
	Status       string  `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *Quote) Reset()                    { *m = Quote{} }
func (m *Quote) String() string            { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()               {}
func (*Quote) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

type Candle struct {
	InstrumentId string  `protobuf:"bytes,1,opt,name=instrumentId" json:"instrumentId,omitempty"`
	Open         float64 `protobuf:"fixed64,2,opt,name=open" json:"open,omitempty"`
	High         float64 `protobuf:"fixed64,3,opt,name=high" json:"high,omitempty"`
	Low          float64 `protobuf:"fixed64,4,opt,name=low" json:"low,omitempty"`
	Close        float64 `protobuf:"fixed64,5,opt,name=close" json:"close,omitempty"`
	Time         string  `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	Status       string  `protobuf:"bytes,7,opt,name=status" json:"status,omitempty"`
}

func (m *Candle) Reset()                    { *m = Candle{} }
func (m *Candle) String() string            { return proto.CompactTextString(m) }
func (*Candle) ProtoMessage()               {}
func (*Candle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type Instrument struct {
	InstrumentId  string `protobuf:"bytes,1,opt,name=instrumentId" json:"instrumentId,omitempty"`
	DisplayName   string `protobuf:"bytes,2,opt,name=displayName" json:"displayName,omitempty"`
	Pip           string `protobuf:"bytes,3,opt,name=pip" json:"pip,omitempty"`
	MaxTradeUnits int32  `protobuf:"varint,4,opt,name=maxTradeUnits" json:"maxTradeUnits,omitempty"`
}

func (m *Instrument) Reset()                    { *m = Instrument{} }
func (m *Instrument) String() string            { return proto.CompactTextString(m) }
func (*Instrument) ProtoMessage()               {}
func (*Instrument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type Account struct {
	Id         string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Currency   string  `protobuf:"bytes,3,opt,name=currency" json:"currency,omitempty"`
	MarginRate float64 `protobuf:"fixed64,4,opt,name=marginRate" json:"marginRate,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type AccountInfo struct {
	Id           string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Currency     string  `protobuf:"bytes,3,opt,name=currency" json:"currency,omitempty"`
	MarginRate   float64 `protobuf:"fixed64,4,opt,name=margin_rate,json=marginRate" json:"margin_rate,omitempty"`
	Balance      float64 `protobuf:"fixed64,5,opt,name=balance" json:"balance,omitempty"`
	UnrealizedPl float64 `protobuf:"fixed64,6,opt,name=unrealized_pl,json=unrealizedPl" json:"unrealized_pl,omitempty"`
	RealizedPl   float64 `protobuf:"fixed64,7,opt,name=realized_pl,json=realizedPl" json:"realized_pl,omitempty"`
	MarginUsed   float64 `protobuf:"fixed64,8,opt,name=margin_used,json=marginUsed" json:"margin_used,omitempty"`
	MarginAvail  float64 `protobuf:"fixed64,9,opt,name=margin_avail,json=marginAvail" json:"margin_avail,omitempty"`
	OpenTrades   float64 `protobuf:"fixed64,10,opt,name=open_trades,json=openTrades" json:"open_trades,omitempty"`
	OpenOrders   float64 `protobuf:"fixed64,11,opt,name=open_orders,json=openOrders" json:"open_orders,omitempty"`
}

func (m *AccountInfo) Reset()                    { *m = AccountInfo{} }
func (m *AccountInfo) String() string            { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()               {}
func (*AccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type Order struct {
	Id           string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	InstrumentId string  `protobuf:"bytes,2,opt,name=instrumentId" json:"instrumentId,omitempty"`
	Units        int32   `protobuf:"varint,3,opt,name=units" json:"units,omitempty"`
	Side         string  `protobuf:"bytes,4,opt,name=side" json:"side,omitempty"`
	Type         string  `protobuf:"bytes,5,opt,name=type" json:"type,omitempty"`
	Time         string  `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	Price        float64 `protobuf:"fixed64,7,opt,name=price" json:"price,omitempty"`
	TakeProfit   float64 `protobuf:"fixed64,8,opt,name=take_profit,json=takeProfit" json:"take_profit,omitempty"`
	StopLoss     float64 `protobuf:"fixed64,9,opt,name=stop_loss,json=stopLoss" json:"stop_loss,omitempty"`
	Expiry       string  `protobuf:"bytes,10,opt,name=expiry" json:"expiry,omitempty"`
	UpperBound   float64 `protobuf:"fixed64,11,opt,name=upper_bound,json=upperBound" json:"upper_bound,omitempty"`
	LowerBound   float64 `protobuf:"fixed64,12,opt,name=lower_bound,json=lowerBound" json:"lower_bound,omitempty"`
	TrailingStop float64 `protobuf:"fixed64,13,opt,name=trailing_stop,json=trailingStop" json:"trailing_stop,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func init() {
	proto.RegisterType((*InstrumentListReq)(nil), "protos.InstrumentListReq")
	proto.RegisterType((*InstrumentListResp)(nil), "protos.InstrumentListResp")
	proto.RegisterType((*PriceListReq)(nil), "protos.PriceListReq")
	proto.RegisterType((*PriceListResp)(nil), "protos.PriceListResp")
	proto.RegisterType((*LastCandleReq)(nil), "protos.LastCandleReq")
	proto.RegisterType((*LastCandleResp)(nil), "protos.LastCandleResp")
	proto.RegisterType((*StreamPricesReq)(nil), "protos.StreamPricesReq")
	proto.RegisterType((*StreamCandleReq)(nil), "protos.StreamCandleReq")
	proto.RegisterType((*AccountListReq)(nil), "protos.AccountListReq")
	proto.RegisterType((*AccountListResp)(nil), "protos.AccountListResp")
	proto.RegisterType((*AccountInfoReq)(nil), "protos.AccountInfoReq")
	proto.RegisterType((*AccountInfoResp)(nil), "protos.AccountInfoResp")
	proto.RegisterType((*OrderListReq)(nil), "protos.OrderListReq")
	proto.RegisterType((*OrderListResp)(nil), "protos.OrderListResp")
	proto.RegisterType((*CloseTradeReq)(nil), "protos.CloseTradeReq")
	proto.RegisterType((*CloseTradeResp)(nil), "protos.CloseTradeResp")
	proto.RegisterType((*OrderCreationReq)(nil), "protos.OrderCreationReq")
	proto.RegisterType((*OrderCreationResp)(nil), "protos.OrderCreationResp")
	proto.RegisterType((*Quote)(nil), "protos.Quote")
	proto.RegisterType((*Candle)(nil), "protos.Candle")
	proto.RegisterType((*Empty)(nil), "protos.Empty")
	proto.RegisterType((*Instrument)(nil), "protos.Instrument")
	proto.RegisterType((*Account)(nil), "protos.Account")
	proto.RegisterType((*AccountInfo)(nil), "protos.AccountInfo")
	proto.RegisterType((*Order)(nil), "protos.Order")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Broker service

type BrokerClient interface {
	GetInstrumentList(ctx context.Context, in *InstrumentListReq, opts ...grpc.CallOption) (*InstrumentListResp, error)
	GetPrices(ctx context.Context, in *PriceListReq, opts ...grpc.CallOption) (*PriceListResp, error)
	GetLastCandle(ctx context.Context, in *LastCandleReq, opts ...grpc.CallOption) (*LastCandleResp, error)
	StreamPrices(ctx context.Context, in *StreamPricesReq, opts ...grpc.CallOption) (Broker_StreamPricesClient, error)
	StreamCandle(ctx context.Context, in *StreamCandleReq, opts ...grpc.CallOption) (Broker_StreamCandleClient, error)
	GetAccounts(ctx context.Context, in *AccountListReq, opts ...grpc.CallOption) (*AccountListResp, error)
	GetAccountInfo(ctx context.Context, in *AccountInfoReq, opts ...grpc.CallOption) (*AccountInfoResp, error)
	GetOrders(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error)
	CreateOrder(ctx context.Context, in *OrderCreationReq, opts ...grpc.CallOption) (*OrderCreationResp, error)
	CloseTrade(ctx context.Context, in *CloseTradeReq, opts ...grpc.CallOption) (*CloseTradeResp, error)
}

type brokerClient struct {
	cc *grpc.ClientConn
}

func NewBrokerClient(cc *grpc.ClientConn) BrokerClient {
	return &brokerClient{cc}
}

func (c *brokerClient) GetInstrumentList(ctx context.Context, in *InstrumentListReq, opts ...grpc.CallOption) (*InstrumentListResp, error) {
	out := new(InstrumentListResp)
	err := grpc.Invoke(ctx, "/protos.Broker/GetInstrumentList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetPrices(ctx context.Context, in *PriceListReq, opts ...grpc.CallOption) (*PriceListResp, error) {
	out := new(PriceListResp)
	err := grpc.Invoke(ctx, "/protos.Broker/GetPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetLastCandle(ctx context.Context, in *LastCandleReq, opts ...grpc.CallOption) (*LastCandleResp, error) {
	out := new(LastCandleResp)
	err := grpc.Invoke(ctx, "/protos.Broker/GetLastCandle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) StreamPrices(ctx context.Context, in *StreamPricesReq, opts ...grpc.CallOption) (Broker_StreamPricesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Broker_serviceDesc.Streams[0], c.cc, "/protos.Broker/StreamPrices", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerStreamPricesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_StreamPricesClient interface {
	Recv() (*Quote, error)
	grpc.ClientStream
}

type brokerStreamPricesClient struct {
	grpc.ClientStream
}

func (x *brokerStreamPricesClient) Recv() (*Quote, error) {
	m := new(Quote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *brokerClient) StreamCandle(ctx context.Context, in *StreamCandleReq, opts ...grpc.CallOption) (Broker_StreamCandleClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Broker_serviceDesc.Streams[1], c.cc, "/protos.Broker/StreamCandle", opts...)
	if err != nil {
		return nil, err
	}
	x := &brokerStreamCandleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Broker_StreamCandleClient interface {
	Recv() (*Candle, error)
	grpc.ClientStream
}

type brokerStreamCandleClient struct {
	grpc.ClientStream
}

func (x *brokerStreamCandleClient) Recv() (*Candle, error) {
	m := new(Candle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *brokerClient) GetAccounts(ctx context.Context, in *AccountListReq, opts ...grpc.CallOption) (*AccountListResp, error) {
	out := new(AccountListResp)
	err := grpc.Invoke(ctx, "/protos.Broker/GetAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetAccountInfo(ctx context.Context, in *AccountInfoReq, opts ...grpc.CallOption) (*AccountInfoResp, error) {
	out := new(AccountInfoResp)
	err := grpc.Invoke(ctx, "/protos.Broker/GetAccountInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) GetOrders(ctx context.Context, in *OrderListReq, opts ...grpc.CallOption) (*OrderListResp, error) {
	out := new(OrderListResp)
	err := grpc.Invoke(ctx, "/protos.Broker/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) CreateOrder(ctx context.Context, in *OrderCreationReq, opts ...grpc.CallOption) (*OrderCreationResp, error) {
	out := new(OrderCreationResp)
	err := grpc.Invoke(ctx, "/protos.Broker/CreateOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerClient) CloseTrade(ctx context.Context, in *CloseTradeReq, opts ...grpc.CallOption) (*CloseTradeResp, error) {
	out := new(CloseTradeResp)
	err := grpc.Invoke(ctx, "/protos.Broker/CloseTrade", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Broker service

type BrokerServer interface {
	GetInstrumentList(context.Context, *InstrumentListReq) (*InstrumentListResp, error)
	GetPrices(context.Context, *PriceListReq) (*PriceListResp, error)
	GetLastCandle(context.Context, *LastCandleReq) (*LastCandleResp, error)
	StreamPrices(*StreamPricesReq, Broker_StreamPricesServer) error
	StreamCandle(*StreamCandleReq, Broker_StreamCandleServer) error
	GetAccounts(context.Context, *AccountListReq) (*AccountListResp, error)
	GetAccountInfo(context.Context, *AccountInfoReq) (*AccountInfoResp, error)
	GetOrders(context.Context, *OrderListReq) (*OrderListResp, error)
	CreateOrder(context.Context, *OrderCreationReq) (*OrderCreationResp, error)
	CloseTrade(context.Context, *CloseTradeReq) (*CloseTradeResp, error)
}

func RegisterBrokerServer(s *grpc.Server, srv BrokerServer) {
	s.RegisterService(&_Broker_serviceDesc, srv)
}

func _Broker_GetInstrumentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstrumentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetInstrumentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetInstrumentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetInstrumentList(ctx, req.(*InstrumentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetPrices(ctx, req.(*PriceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetLastCandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastCandleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetLastCandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetLastCandle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetLastCandle(ctx, req.(*LastCandleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_StreamPrices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPricesReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).StreamPrices(m, &brokerStreamPricesServer{stream})
}

type Broker_StreamPricesServer interface {
	Send(*Quote) error
	grpc.ServerStream
}

type brokerStreamPricesServer struct {
	grpc.ServerStream
}

func (x *brokerStreamPricesServer) Send(m *Quote) error {
	return x.ServerStream.SendMsg(m)
}

func _Broker_StreamCandle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCandleReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BrokerServer).StreamCandle(m, &brokerStreamCandleServer{stream})
}

type Broker_StreamCandleServer interface {
	Send(*Candle) error
	grpc.ServerStream
}

type brokerStreamCandleServer struct {
	grpc.ServerStream
}

func (x *brokerStreamCandleServer) Send(m *Candle) error {
	return x.ServerStream.SendMsg(m)
}

func _Broker_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetAccounts(ctx, req.(*AccountListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetAccountInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetAccountInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetAccountInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetAccountInfo(ctx, req.(*AccountInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).GetOrders(ctx, req.(*OrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCreationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).CreateOrder(ctx, req.(*OrderCreationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Broker_CloseTrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTradeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServer).CloseTrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Broker/CloseTrade",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServer).CloseTrade(ctx, req.(*CloseTradeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Broker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Broker",
	HandlerType: (*BrokerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstrumentList",
			Handler:    _Broker_GetInstrumentList_Handler,
		},
		{
			MethodName: "GetPrices",
			Handler:    _Broker_GetPrices_Handler,
		},
		{
			MethodName: "GetLastCandle",
			Handler:    _Broker_GetLastCandle_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _Broker_GetAccounts_Handler,
		},
		{
			MethodName: "GetAccountInfo",
			Handler:    _Broker_GetAccountInfo_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _Broker_GetOrders_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Broker_CreateOrder_Handler,
		},
		{
			MethodName: "CloseTrade",
			Handler:    _Broker_CloseTrade_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPrices",
			Handler:       _Broker_StreamPrices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamCandle",
			Handler:       _Broker_StreamCandle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("protos/broker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x57, 0xeb, 0x6e, 0x1c, 0x35,
	0x14, 0xce, 0x64, 0x6f, 0xd9, 0xb3, 0x97, 0x24, 0x6e, 0x49, 0xa7, 0x0b, 0xa2, 0xc1, 0xdc, 0x2a,
	0x81, 0x02, 0xa4, 0x80, 0x50, 0x11, 0xa8, 0x6d, 0x40, 0x28, 0x28, 0xa2, 0x61, 0x4a, 0x7f, 0xaf,
	0x66, 0x77, 0xdc, 0xd4, 0xca, 0xec, 0xcc, 0x64, 0xec, 0x85, 0x2c, 0xbc, 0x01, 0xff, 0xf9, 0xc3,
	0x13, 0xf0, 0x40, 0x3c, 0x00, 0x8f, 0x82, 0x7d, 0xec, 0xb9, 0xee, 0x44, 0x2c, 0x42, 0xfc, 0xb3,
	0x3f, 0x7f, 0x3e, 0xdf, 0x99, 0x73, 0xf1, 0x9e, 0x85, 0x5b, 0x49, 0x1a, 0xcb, 0x58, 0x7c, 0x30,
	0x4b, 0xe3, 0x4b, 0x96, 0x1e, 0xe1, 0x8e, 0x74, 0x0d, 0x48, 0x3f, 0x82, 0xfd, 0xd3, 0x48, 0xc8,
	0x74, 0xb9, 0x60, 0x91, 0x3c, 0xe3, 0x42, 0x7a, 0xec, 0x8a, 0xbc, 0x06, 0x7d, 0x7f, 0x3e, 0x8f,
	0x97, 0x91, 0x3c, 0x0d, 0xdc, 0xed, 0x43, 0xe7, 0x7e, 0xdf, 0x2b, 0x00, 0xfa, 0x2d, 0x90, 0xfa,
	0x15, 0x91, 0x90, 0x8f, 0x61, 0xc0, 0x73, 0x54, 0xb8, 0xce, 0x61, 0xeb, 0xfe, 0xe0, 0x98, 0x18,
	0x35, 0x71, 0x54, 0x5c, 0xf0, 0xca, 0x34, 0x7a, 0x0c, 0xc3, 0xf3, 0x94, 0xcf, 0x59, 0xa6, 0x4c,
	0x61, 0x58, 0x1c, 0xa3, 0x78, 0x4b, 0x89, 0x57, 0x30, 0xfa, 0x29, 0x8c, 0x4a, 0x77, 0x94, 0xf4,
	0xdb, 0xd0, 0xbd, 0x5a, 0xc6, 0x92, 0x65, 0xaa, 0xa3, 0x4c, 0xf5, 0x7b, 0x8d, 0x7a, 0xf6, 0x90,
	0x3e, 0x80, 0xd1, 0x99, 0x2f, 0xe4, 0x89, 0x1f, 0x05, 0x21, 0x6b, 0x16, 0x73, 0xd6, 0xc4, 0x3e,
	0x83, 0x71, 0xf9, 0x92, 0x52, 0x7b, 0x07, 0xba, 0x73, 0xdc, 0x29, 0x35, 0x47, 0xa9, 0x8d, 0x33,
	0x35, 0xcb, 0xb1, 0xa7, 0xf4, 0x13, 0xd8, 0x7d, 0x26, 0x53, 0xe6, 0x2f, 0xd0, 0x59, 0xb1, 0xa9,
	0x60, 0x7e, 0xed, 0xdf, 0xf9, 0xb9, 0x07, 0xe3, 0xc7, 0x26, 0x43, 0x36, 0x94, 0xf4, 0x4b, 0xd8,
	0xad, 0x20, 0xca, 0xf5, 0xf7, 0x60, 0xc7, 0xa6, 0x31, 0x0b, 0xd5, 0x6e, 0xe6, 0xbc, 0xa5, 0x7a,
	0x39, 0x81, 0x1e, 0xe5, 0x16, 0x4f, 0xa3, 0x17, 0xf1, 0x3f, 0x97, 0xc5, 0xc3, 0x5c, 0xcf, 0xf0,
	0x95, 0xde, 0xbb, 0xd0, 0xe6, 0x6a, 0x6d, 0x03, 0x75, 0xab, 0xa6, 0x85, 0x34, 0x24, 0xd0, 0xf7,
	0x61, 0xf8, 0x34, 0x0d, 0x58, 0xba, 0x59, 0x01, 0xaa, 0x02, 0x28, 0xb1, 0x4d, 0x01, 0xc4, 0x1a,
	0x58, 0x2b, 0x00, 0xa4, 0x79, 0xf6, 0x90, 0xde, 0x83, 0xd1, 0x49, 0x18, 0x0b, 0xf6, 0x43, 0xea,
	0x07, 0x18, 0xd8, 0x31, 0x6c, 0xf3, 0x00, 0xbd, 0xeb, 0x7b, 0x6a, 0x45, 0x7f, 0x77, 0x60, 0x5c,
	0x66, 0x28, 0xd3, 0x35, 0x0a, 0xb9, 0x0d, 0x9d, 0x44, 0xe7, 0x13, 0xbd, 0x72, 0x3c, 0xb3, 0x59,
	0xcb, 0x50, 0x6b, 0x3d, 0x43, 0x84, 0x40, 0x5b, 0xf2, 0x05, 0x73, 0xdb, 0x78, 0x86, 0x6b, 0x72,
	0x00, 0xba, 0x0f, 0x5f, 0x70, 0xe9, 0x76, 0xd0, 0x9c, 0xdd, 0x69, 0xae, 0xe0, 0x01, 0x73, 0xbb,
	0x86, 0xab, 0xd7, 0x54, 0xc2, 0x1e, 0x7e, 0xce, 0x89, 0x2a, 0x0e, 0xc9, 0xe3, 0x68, 0xc3, 0xca,
	0xd0, 0x1e, 0x2f, 0x23, 0xae, 0x32, 0xae, 0x9d, 0xea, 0x78, 0x66, 0x93, 0x2b, 0xb4, 0x0b, 0x05,
	0xf4, 0x70, 0x95, 0x30, 0xf4, 0x45, 0x7b, 0xa8, 0xd6, 0xf4, 0x0a, 0xf6, 0x6b, 0xaa, 0x2a, 0x28,
	0x75, 0x59, 0xa7, 0x59, 0xb6, 0x21, 0x50, 0x59, 0x10, 0x5a, 0xa5, 0x20, 0x98, 0x10, 0xb7, 0xf3,
	0x2c, 0xfc, 0x02, 0x1d, 0x6c, 0xdc, 0x8d, 0x64, 0xf6, 0xa0, 0x35, 0xe3, 0x81, 0x15, 0xd1, 0x4b,
	0x8d, 0xf8, 0xe2, 0x12, 0x15, 0x14, 0xa2, 0x96, 0x37, 0x45, 0x5e, 0x48, 0x5f, 0x2e, 0x85, 0xfd,
	0x5a, 0xbb, 0xa3, 0x7f, 0x38, 0xd0, 0x35, 0x9d, 0xb7, 0x91, 0xbc, 0x32, 0x1d, 0x27, 0x2c, 0xb2,
	0xfa, 0xb8, 0xd6, 0xd8, 0x4b, 0x7e, 0xf1, 0xd2, 0x7a, 0x80, 0x6b, 0xed, 0x54, 0x18, 0xff, 0x84,
	0x1e, 0x28, 0xa7, 0xd4, 0x52, 0xc7, 0x67, 0xae, 0x4b, 0xcd, 0x66, 0xde, 0x6c, 0x72, 0x57, 0xbb,
	0x8d, 0xae, 0xf6, 0x2a, 0xae, 0xf6, 0xa0, 0xf3, 0xf5, 0x22, 0x91, 0x2b, 0xfa, 0xab, 0x03, 0x50,
	0x3c, 0xb0, 0x1b, 0xf9, 0x7d, 0x08, 0x83, 0x80, 0x8b, 0x24, 0xf4, 0x57, 0xdf, 0xf9, 0x0b, 0x66,
	0xeb, 0xa6, 0x0c, 0x69, 0x8f, 0x13, 0x9e, 0xd8, 0x44, 0xe9, 0x25, 0x79, 0x0b, 0x46, 0x0b, 0xff,
	0x1a, 0x5b, 0xe3, 0x39, 0x16, 0x54, 0x1b, 0x0b, 0xaa, 0x0a, 0x52, 0x0e, 0x3d, 0xdb, 0xdf, 0x6b,
	0xbd, 0xa3, 0x3e, 0x2e, 0x2a, 0xd4, 0x70, 0x4d, 0x26, 0xb0, 0x33, 0x5f, 0xa6, 0x29, 0x8b, 0xe6,
	0x2b, 0xab, 0x95, 0xef, 0xc9, 0xeb, 0x00, 0x0b, 0x3f, 0xbd, 0xe0, 0x91, 0xe7, 0x4b, 0x66, 0x63,
	0x57, 0x42, 0xe8, 0x9f, 0xdb, 0x30, 0x28, 0xbd, 0x25, 0xff, 0x59, 0xef, 0x1e, 0x0c, 0x8c, 0xf5,
	0x69, 0xda, 0x28, 0x48, 0x5c, 0xe8, 0xcd, 0xfc, 0xd0, 0x8f, 0xe6, 0x59, 0xd6, 0xb2, 0x2d, 0x79,
	0x13, 0x46, 0xcb, 0x48, 0xb5, 0x48, 0xc8, 0x7f, 0x66, 0xc1, 0x34, 0x09, 0x31, 0x81, 0x8e, 0x37,
	0x2c, 0xc0, 0xf3, 0x50, 0xdb, 0x2f, 0x53, 0x7a, 0xc6, 0x7e, 0x95, 0x60, 0x1d, 0x58, 0x0a, 0x16,
	0xb8, 0x3b, 0x65, 0x07, 0x9e, 0x2b, 0x84, 0xbc, 0x01, 0x43, 0x4b, 0xf0, 0x7f, 0xf4, 0x79, 0xe8,
	0xf6, 0x91, 0x61, 0x2f, 0x3d, 0xd6, 0x90, 0xb6, 0xa1, 0xab, 0x70, 0x2a, 0x75, 0x4a, 0x84, 0x0b,
	0xc6, 0x86, 0x86, 0x30, 0x49, 0x22, 0x27, 0xd8, 0x17, 0x73, 0x50, 0x10, 0x9e, 0x9a, 0x67, 0xf2,
	0xaf, 0x6d, 0xe8, 0xe0, 0x72, 0x2d, 0xa0, 0xff, 0xfb, 0x73, 0xd3, 0x58, 0xff, 0xf9, 0x4b, 0xd2,
	0x2b, 0xbf, 0x24, 0xea, 0x33, 0xa4, 0x7f, 0xc9, 0xa6, 0xf6, 0xfd, 0xb4, 0xb1, 0xd2, 0xd0, 0xb9,
	0x79, 0x43, 0x5f, 0x85, 0xbe, 0x90, 0x71, 0x32, 0x55, 0x7d, 0x25, 0x6c, 0xa0, 0x76, 0x34, 0x70,
	0xa6, 0xf6, 0xba, 0xa7, 0xd8, 0x75, 0xc2, 0xd3, 0x15, 0x06, 0x48, 0xf5, 0x94, 0xd9, 0x69, 0xab,
	0xcb, 0x24, 0x61, 0xe9, 0x74, 0xa6, 0xaa, 0x2a, 0xc8, 0x82, 0x83, 0xd0, 0x13, 0x8d, 0x68, 0x82,
	0xea, 0xde, 0x9c, 0x30, 0x34, 0x04, 0x84, 0x0c, 0x41, 0x55, 0x82, 0x0a, 0x3d, 0x0f, 0x79, 0x74,
	0x31, 0xd5, 0x72, 0xee, 0xc8, 0x54, 0x42, 0x06, 0x3e, 0x53, 0xd8, 0xf1, 0x6f, 0x1d, 0xe8, 0x3e,
	0xc1, 0x71, 0x8c, 0x9c, 0xc1, 0xfe, 0x37, 0x4c, 0x56, 0x07, 0x2a, 0x72, 0x77, 0x7d, 0x6e, 0xb2,
	0x3f, 0x8d, 0x93, 0xc9, 0x4d, 0x47, 0x22, 0xa1, 0x5b, 0xe4, 0x21, 0xf4, 0x95, 0x35, 0x33, 0x71,
	0x90, 0xdb, 0x19, 0xb5, 0x3c, 0x62, 0x4d, 0x5e, 0x69, 0x40, 0xf1, 0xee, 0x23, 0x18, 0xa9, 0xbb,
	0xc5, 0xb4, 0x43, 0x72, 0x66, 0x65, 0x6c, 0x9a, 0x1c, 0x34, 0xc1, 0x56, 0x7d, 0x58, 0x1e, 0x79,
	0xc8, 0x9d, 0x8c, 0x59, 0x1b, 0x84, 0x26, 0xd5, 0x09, 0x8d, 0x6e, 0x7d, 0xe8, 0x90, 0xcf, 0xb3,
	0xbb, 0x56, 0xbc, 0x76, 0xb7, 0x90, 0xaf, 0xcd, 0x5b, 0x78, 0xf9, 0x11, 0x0c, 0x94, 0xeb, 0xf6,
	0x2d, 0x50, 0xd9, 0xad, 0x4d, 0x1a, 0xd9, 0xa7, 0xdf, 0x69, 0xc4, 0xd1, 0xf5, 0x13, 0x18, 0x17,
	0x16, 0xf0, 0x35, 0x39, 0x68, 0x1a, 0x57, 0x1a, 0x8c, 0x64, 0xd3, 0x4e, 0x1e, 0x7d, 0xd3, 0x46,
	0x45, 0xf4, 0xcb, 0x93, 0x4d, 0x11, 0xfd, 0xca, 0x04, 0xa3, 0xee, 0x7e, 0x05, 0x03, 0xfc, 0x8d,
	0x65, 0xa6, 0xf5, 0xdc, 0x0a, 0xaf, 0xf4, 0x9b, 0x3f, 0xb9, 0x7b, 0xc3, 0x09, 0x5a, 0xf9, 0x02,
	0xa0, 0x18, 0x60, 0x8a, 0x04, 0x56, 0xc6, 0x9e, 0x22, 0x81, 0xd5, 0x59, 0x87, 0x6e, 0xcd, 0xcc,
	0xbf, 0x82, 0x07, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xcd, 0x54, 0x61, 0x33, 0x0c, 0x00,
	0x00,
}
